"""Initial weather and air quality tables

Revision ID: a58302a53253
Revises: 
Create Date: 2025-04-06 16:30:29.652702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58302a53253'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='winddirectionenum'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('carbon_monoxide', sa.Float(), nullable=True),
    sa.Column('ozone', sa.Float(), nullable=True),
    sa.Column('nitrogen_dioxide', sa.Float(), nullable=True),
    sa.Column('sulphur_dioxide', sa.Float(), nullable=True),
    sa.Column('pm2_5', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('us_epa_index', sa.Integer(), nullable=True),
    sa.Column('gb_defra_index', sa.Integer(), nullable=True),
    sa.Column('go_outside', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_quality')
    op.drop_table('weather')
    # ### end Alembic commands ###
